# Generated by Django 5.2.11 on 2026-02-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Email of the tenant registrant (admin)', max_length=254),
        ),
    ]
