# Generated by Django 5.2.11 on 2026-02-22 23:19

import django.db.models.deletion
import management.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Email of the tenant registrant', max_length=254),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='neon_db_password',
            field=management.tenants.models.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='TenantMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('admin', 'Admin')], default='agent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__slug', 'email'],
                'unique_together': {('tenant', 'email')},
            },
        ),
    ]
