# Generated by Django 5.2.11 on 2026-02-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agent',
            managers=[
            ],
        ),
    ]
