import { Ticket } from "@/types/ticket";

export const mockTickets: Ticket[] = [
  {
    id: 1001,
    subject: "Bestellung #8234 nicht erhalten",
    customerName: "Anna Mueller",
    customerEmail: "anna.mueller@gmail.com",
    status: "open",
    priority: "high",
    channel: "email",
    assignee: "Max Weber",
    tags: ["versand", "dringend"],
    createdAt: "2026-02-20T09:15:00Z",
    updatedAt: "2026-02-20T10:30:00Z",
    messages: [
      { id: "m1", sender: "Anna Mueller", body: "Hallo, ich habe meine Bestellung #8234 vor 10 Tagen aufgegeben und sie ist immer noch nicht angekommen. Koennen Sie bitte den Status pruefen?", timestamp: "2026-02-20T09:15:00Z" },
      { id: "m2", sender: "Max Weber", body: "Guten Tag Frau Mueller, ich pruefe das sofort fuer Sie. Koennen Sie mir bitte Ihre Lieferadresse bestaetigen?", timestamp: "2026-02-20T10:30:00Z" },
      { id: "m3", sender: "Anna Mueller", body: "Musterstrasse 12, 10115 Berlin. Danke!", timestamp: "2026-02-20T10:45:00Z" },
    ],
  },
  {
    id: 1002,
    subject: "Rueckerstattung fuer defektes Produkt",
    customerName: "Thomas Schmidt",
    customerEmail: "t.schmidt@web.de",
    status: "pending",
    priority: "medium",
    channel: "chat",
    assignee: "Lisa Braun",
    tags: ["rueckerstattung", "defekt"],
    createdAt: "2026-02-19T14:22:00Z",
    updatedAt: "2026-02-20T08:00:00Z",
    messages: [
      { id: "m4", sender: "Thomas Schmidt", body: "Das Produkt kam beschaedigt an. Ich moechte eine Rueckerstattung.", timestamp: "2026-02-19T14:22:00Z" },
      { id: "m5", sender: "Lisa Braun", body: "Es tut mir leid das zu hoeren. Koennten Sie bitte ein Foto des Schadens schicken?", timestamp: "2026-02-19T15:00:00Z" },
    ],
  },
  {
    id: 1003,
    subject: "Passwort zuruecksetzen funktioniert nicht",
    customerName: "Sarah Klein",
    customerEmail: "sarah.klein@outlook.de",
    status: "open",
    priority: "urgent",
    channel: "phone",
    assignee: "Max Weber",
    tags: ["account", "login"],
    createdAt: "2026-02-20T11:00:00Z",
    updatedAt: "2026-02-20T11:30:00Z",
    messages: [
      { id: "m6", sender: "Sarah Klein", body: "Ich kann mein Passwort nicht zuruecksetzen. Die E-Mail kommt einfach nicht an.", timestamp: "2026-02-20T11:00:00Z" },
      { id: "m7", sender: "Max Weber", body: "Ich sehe, dass die E-Mail-Adresse in unserem System anders hinterlegt ist. Ich korrigiere das.", timestamp: "2026-02-20T11:30:00Z" },
    ],
  },
  {
    id: 1004,
    subject: "Frage zur Groessentabelle",
    customerName: "Julia Fischer",
    customerEmail: "j.fischer@gmx.de",
    status: "closed",
    priority: "low",
    channel: "chat",
    assignee: "Lisa Braun",
    tags: ["produktinfo"],
    createdAt: "2026-02-18T16:45:00Z",
    updatedAt: "2026-02-18T17:20:00Z",
    messages: [
      { id: "m8", sender: "Julia Fischer", body: "Ich bin unsicher welche Groesse ich bestellen soll. Koennten Sie mir helfen?", timestamp: "2026-02-18T16:45:00Z" },
      { id: "m9", sender: "Lisa Braun", body: "Natuerlich! Wie gross sind Sie und welches Gewicht haben Sie ungefaehr? Dann kann ich Ihnen die passende Groesse empfehlen.", timestamp: "2026-02-18T17:00:00Z" },
      { id: "m10", sender: "Julia Fischer", body: "168cm, ca. 62kg.", timestamp: "2026-02-18T17:10:00Z" },
      { id: "m11", sender: "Lisa Braun", body: "Dann empfehle ich Ihnen Groesse M. Die passt bei Ihren Massen perfekt.", timestamp: "2026-02-18T17:20:00Z" },
    ],
  },
  {
    id: 1005,
    subject: "Lieferung an falsche Adresse",
    customerName: "Michael Bauer",
    customerEmail: "m.bauer@yahoo.de",
    status: "open",
    priority: "high",
    channel: "email",
    assignee: "Nicht zugewiesen",
    tags: ["versand", "adresse"],
    createdAt: "2026-02-20T08:30:00Z",
    updatedAt: "2026-02-20T08:30:00Z",
    messages: [
      { id: "m12", sender: "Michael Bauer", body: "Mein Paket wurde an meine alte Adresse geliefert. Bitte helfen Sie mir, das umzuleiten.", timestamp: "2026-02-20T08:30:00Z" },
    ],
  },
  {
    id: 1006,
    subject: "Rabattcode funktioniert nicht",
    customerName: "Laura Hoffmann",
    customerEmail: "laura.h@gmail.com",
    status: "pending",
    priority: "low",
    channel: "social",
    assignee: "Max Weber",
    tags: ["rabatt", "bestellung"],
    createdAt: "2026-02-19T20:15:00Z",
    updatedAt: "2026-02-20T09:00:00Z",
    messages: [
      { id: "m13", sender: "Laura Hoffmann", body: "Ich habe den Code WINTER20 eingegeben, aber er wird nicht akzeptiert.", timestamp: "2026-02-19T20:15:00Z" },
      { id: "m14", sender: "Max Weber", body: "Der Code ist leider am 15.02. abgelaufen. Ich kann Ihnen aber einen neuen 15%-Code anbieten: SPRING15", timestamp: "2026-02-20T09:00:00Z" },
    ],
  },
  {
    id: 1007,
    subject: "Abo kuendigen",
    customerName: "Peter Wagner",
    customerEmail: "p.wagner@t-online.de",
    status: "closed",
    priority: "medium",
    channel: "phone",
    assignee: "Lisa Braun",
    tags: ["abo", "kuendigung"],
    createdAt: "2026-02-17T10:00:00Z",
    updatedAt: "2026-02-17T11:00:00Z",
    messages: [
      { id: "m15", sender: "Peter Wagner", body: "Ich moechte mein Premium-Abo zum Monatsende kuendigen.", timestamp: "2026-02-17T10:00:00Z" },
      { id: "m16", sender: "Lisa Braun", body: "Ihr Abo wurde zum 28.02. gekuendigt. Sie erhalten eine Bestaetigung per E-Mail.", timestamp: "2026-02-17T11:00:00Z" },
    ],
  },
  {
    id: 1008,
    subject: "Doppelte Abbuchung auf Konto",
    customerName: "Katrin Meyer",
    customerEmail: "katrin.meyer@posteo.de",
    status: "open",
    priority: "urgent",
    channel: "email",
    assignee: "Max Weber",
    tags: ["zahlung", "dringend"],
    createdAt: "2026-02-20T07:45:00Z",
    updatedAt: "2026-02-20T09:15:00Z",
    messages: [
      { id: "m17", sender: "Katrin Meyer", body: "Mir wurde der Betrag von 89,99 EUR zweimal abgebucht! Bitte korrigieren Sie das sofort.", timestamp: "2026-02-20T07:45:00Z" },
      { id: "m18", sender: "Max Weber", body: "Ich sehe die doppelte Buchung. Die Rueckerstattung wird sofort eingeleitet und sollte in 3-5 Werktagen auf Ihrem Konto sein.", timestamp: "2026-02-20T09:15:00Z" },
    ],
  },
  {
    id: 1009,
    subject: "Produktbewertung melden",
    customerName: "Stefan Koch",
    customerEmail: "s.koch@web.de",
    status: "closed",
    priority: "low",
    channel: "social",
    assignee: "Lisa Braun",
    tags: ["bewertung", "moderation"],
    createdAt: "2026-02-16T13:30:00Z",
    updatedAt: "2026-02-16T15:00:00Z",
    messages: [
      { id: "m19", sender: "Stefan Koch", body: "Eine Bewertung auf meinem Produkt enthaelt beleidigende Inhalte. Bitte entfernen.", timestamp: "2026-02-16T13:30:00Z" },
      { id: "m20", sender: "Lisa Braun", body: "Danke fuer den Hinweis. Die Bewertung wurde geprueft und entfernt.", timestamp: "2026-02-16T15:00:00Z" },
    ],
  },
  {
    id: 1010,
    subject: "API-Zugang beantragen",
    customerName: "Frank Richter",
    customerEmail: "f.richter@techfirma.de",
    status: "pending",
    priority: "medium",
    channel: "email",
    assignee: "Nicht zugewiesen",
    tags: ["api", "partner"],
    createdAt: "2026-02-19T11:00:00Z",
    updatedAt: "2026-02-19T11:00:00Z",
    messages: [
      { id: "m21", sender: "Frank Richter", body: "Wir moechten die API-Integration nutzen. Koennen Sie uns bitte Zugangsdaten bereitstellen?", timestamp: "2026-02-19T11:00:00Z" },
    ],
  },
  {
    id: 1011,
    subject: "Falsche Farbe geliefert",
    customerName: "Nicole Schulz",
    customerEmail: "nicole.s@icloud.com",
    status: "open",
    priority: "medium",
    channel: "chat",
    assignee: "Lisa Braun",
    tags: ["versand", "umtausch"],
    createdAt: "2026-02-20T12:00:00Z",
    updatedAt: "2026-02-20T12:30:00Z",
    messages: [
      { id: "m22", sender: "Nicole Schulz", body: "Ich habe blau bestellt, aber schwarz erhalten. Kann ich umtauschen?", timestamp: "2026-02-20T12:00:00Z" },
      { id: "m23", sender: "Lisa Braun", body: "Selbstverstaendlich! Ich schicke Ihnen ein Retourenlabel per E-Mail.", timestamp: "2026-02-20T12:30:00Z" },
    ],
  },
  {
    id: 1012,
    subject: "Newsletter abbestellen",
    customerName: "Martin Wolf",
    customerEmail: "m.wolf@gmail.com",
    status: "closed",
    priority: "low",
    channel: "email",
    assignee: "Max Weber",
    tags: ["newsletter"],
    createdAt: "2026-02-15T09:00:00Z",
    updatedAt: "2026-02-15T09:30:00Z",
    messages: [
      { id: "m24", sender: "Martin Wolf", body: "Bitte nehmen Sie mich aus dem Newsletter-Verteiler.", timestamp: "2026-02-15T09:00:00Z" },
      { id: "m25", sender: "Max Weber", body: "Erledigt. Sie erhalten ab sofort keine Newsletter mehr.", timestamp: "2026-02-15T09:30:00Z" },
    ],
  },
  {
    id: 1013,
    subject: "Rechnung korrigieren",
    customerName: "Claudia Neumann",
    customerEmail: "c.neumann@firma.de",
    status: "pending",
    priority: "high",
    channel: "email",
    assignee: "Max Weber",
    tags: ["rechnung", "korrektur"],
    createdAt: "2026-02-19T15:30:00Z",
    updatedAt: "2026-02-20T08:00:00Z",
    messages: [
      { id: "m26", sender: "Claudia Neumann", body: "Auf der Rechnung #R-4521 ist die falsche Firmenadresse angegeben. Bitte korrigieren.", timestamp: "2026-02-19T15:30:00Z" },
      { id: "m27", sender: "Max Weber", body: "Koennen Sie mir bitte die korrekte Adresse mitteilen?", timestamp: "2026-02-20T08:00:00Z" },
    ],
  },
  {
    id: 1014,
    subject: "App stuerzt beim Checkout ab",
    customerName: "David Braun",
    customerEmail: "d.braun@outlook.de",
    status: "open",
    priority: "urgent",
    channel: "chat",
    assignee: "Nicht zugewiesen",
    tags: ["bug", "app", "dringend"],
    createdAt: "2026-02-20T13:00:00Z",
    updatedAt: "2026-02-20T13:00:00Z",
    messages: [
      { id: "m28", sender: "David Braun", body: "Jedes Mal wenn ich auf 'Bezahlen' klicke, stuerzt die App ab. iPhone 15, iOS 19.1.", timestamp: "2026-02-20T13:00:00Z" },
    ],
  },
  {
    id: 1015,
    subject: "Partnerprogramm Informationen",
    customerName: "Sandra Hartmann",
    customerEmail: "s.hartmann@marketing.de",
    status: "open",
    priority: "low",
    channel: "social",
    assignee: "Lisa Braun",
    tags: ["partner", "info"],
    createdAt: "2026-02-20T10:00:00Z",
    updatedAt: "2026-02-20T10:00:00Z",
    messages: [
      { id: "m29", sender: "Sandra Hartmann", body: "Koennten Sie mir Informationen zu Ihrem Partnerprogramm zukommen lassen?", timestamp: "2026-02-20T10:00:00Z" },
    ],
  },
];
